import type { Person } from "./db/schema";

/**
 * Bundled sample dataset. Used only when `MONGODB_URI` is not configured so the
 * UI renders meaningfully on first run. Photos are Unsplash portraits. Once a
 * database is connected, all data comes from MongoDB instead.
 */
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

const base = {
  nationality: "Venezolana",
  status: "desaparecido" as const,
  reporterName: "Línea SOSVEN",
  reporterPhone: "0800-767-836",
  reporterEmail: "reportes@sosven.org",
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const samplePersons: Person[] = [
  {
    _id: "11111111-1111-1111-1111-111111111111",
    firstName: "Juan Carlos",
    lastName: "Pérez",
    age: 45,
    gender: "masculino",
    idDocument: "V-12.***.***",
    heightCm: 178,
    weightKg: 82,
    build: "Atlética",
    hairColor: "Negro",
    hairLength: "Corto",
    eyeColor: "Marrón",
    skinTone: "Trigueña",
    distinguishingMarks: "Cicatriz pequeña en el pómulo izquierdo.",
    lastSeenLocation: "Av. Francisco de Miranda, Sector El Parque",
    lastSeenCity: "Caracas",
    lastSeenDate: daysAgo(3),
    circumstances:
      "Visto por última vez tras el sismo, ayudando a vecinos a evacuar un edificio.",
    photoUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Hermana",
    ...base,
  },
  {
    _id: "22222222-2222-2222-2222-222222222222",
    firstName: "Mariana",
    lastName: "Silva",
    age: 32,
    gender: "femenino",
    idDocument: "V-18.***.***",
    heightCm: 165,
    weightKg: 60,
    build: "Delgada",
    hairColor: "Castaño",
    hairLength: "Largo",
    eyeColor: "Verde",
    skinTone: "Clara",
    distinguishingMarks: "Lunar visible en la mejilla derecha.",
    lastSeenLocation: "Urbanización La Floresta",
    lastSeenCity: "Caracas",
    lastSeenDate: daysAgo(2),
    circumstances: "Se separó de su familia durante la evacuación.",
    photoUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Esposo",
    ...base,
    status: "encontrado" as const,
  },
  {
    _id: "33333333-3333-3333-3333-333333333333",
    firstName: "Luis Eduardo",
    lastName: "Gómez",
    age: 67,
    gender: "masculino",
    idDocument: "V-5.***.***",
    heightCm: 172,
    weightKg: 75,
    build: "Media",
    hairColor: "Canoso",
    hairLength: "Corto",
    eyeColor: "Marrón",
    skinTone: "Trigueña",
    distinguishingMarks: "Usa lentes y bastón.",
    lastSeenLocation: "Mercado Municipal de Petare",
    lastSeenCity: "Caracas",
    lastSeenDate: daysAgo(4),
    circumstances: "Adulto mayor con movilidad reducida, desorientado tras el sismo.",
    photoUrl:
      "https://images.unsplash.com/photo-1559963110-71b394e7494d?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Hijo",
    ...base,
    status: "encontrado" as const,
  },
  {
    _id: "44444444-4444-4444-4444-444444444444",
    firstName: "Elena",
    lastName: "Rodríguez",
    age: 28,
    gender: "femenino",
    idDocument: "V-20.***.***",
    heightCm: 168,
    weightKg: 58,
    build: "Delgada",
    hairColor: "Castaño claro",
    hairLength: "Medio",
    eyeColor: "Marrón",
    skinTone: "Clara",
    distinguishingMarks: "Tatuaje pequeño en la muñeca izquierda.",
    lastSeenLocation: "Centro de Valencia",
    lastSeenCity: "Valencia",
    lastSeenDate: daysAgo(1),
    circumstances: "No regresó a casa después del temblor.",
    photoUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Madre",
    ...base,
    status: "avistado" as const,
  },
  {
    _id: "55555555-5555-5555-5555-555555555555",
    firstName: "Carlos",
    lastName: "Mendoza",
    age: 12,
    gender: "masculino",
    idDocument: null,
    heightCm: 145,
    weightKg: 40,
    build: "Delgada",
    hairColor: "Negro",
    hairLength: "Corto",
    eyeColor: "Marrón",
    skinTone: "Trigueña",
    distinguishingMarks: "Vestía franela roja y jeans azules.",
    lastSeenLocation: "Escuela Básica Bolivariana",
    lastSeenCity: "Maracay",
    lastSeenDate: daysAgo(2),
    circumstances: "Separado de sus padres durante la evacuación escolar.",
    photoUrl:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Padre",
    ...base,
  },
  {
    _id: "66666666-6666-6666-6666-666666666666",
    firstName: "Rosa",
    lastName: "Martínez",
    age: 71,
    gender: "femenino",
    idDocument: "V-3.***.***",
    heightCm: 158,
    weightKg: 63,
    build: "Media",
    hairColor: "Canoso",
    hairLength: "Corto",
    eyeColor: "Marrón",
    skinTone: "Clara",
    distinguishingMarks: "Camina con dificultad, usa audífono.",
    lastSeenLocation: "Plaza Bolívar de Maracaibo",
    lastSeenCity: "Maracaibo",
    lastSeenDate: daysAgo(3),
    circumstances: "Adulta mayor desaparecida tras evacuación de su residencia.",
    photoUrl:
      "https://images.unsplash.com/photo-1551727974-8af20a3322f1?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Nieta",
    ...base,
  },
  {
    _id: "77777777-7777-7777-7777-777777777777",
    firstName: "Daniela",
    lastName: "Fernández",
    age: 8,
    gender: "femenino",
    idDocument: null,
    heightCm: 128,
    weightKg: 26,
    build: "Delgada",
    hairColor: "Castaño",
    hairLength: "Largo",
    eyeColor: "Marrón",
    skinTone: "Trigueña",
    distinguishingMarks: "Llevaba un morral rosado con dibujos.",
    lastSeenLocation: "Barrio La Vega",
    lastSeenCity: "Caracas",
    lastSeenDate: daysAgo(2),
    circumstances: "Se perdió entre la multitud durante el sismo.",
    photoUrl:
      "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Tía",
    ...base,
    status: "encontrado" as const,
  },
  {
    _id: "88888888-8888-8888-8888-888888888888",
    firstName: "José",
    lastName: "Ramírez",
    age: 39,
    gender: "masculino",
    idDocument: "V-15.***.***",
    heightCm: 180,
    weightKg: 85,
    build: "Robusta",
    hairColor: "Negro",
    hairLength: "Corto",
    eyeColor: "Negro",
    skinTone: "Trigueña",
    distinguishingMarks: "Barba poblada, tatuaje en el antebrazo derecho.",
    lastSeenLocation: "Zona Industrial de Barquisimeto",
    lastSeenCity: "Barquisimeto",
    lastSeenDate: daysAgo(5),
    circumstances: "No se ha sabido de él desde el día del terremoto.",
    photoUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=70",
    reporterRelationship: "Hermano",
    ...base,
  },
];

export const sampleStats = { desaparecidos: 2847, avistados: 562, encontrados: 1234 };
